### ISSUE TITLE
Tool names "Backpack Components"

### ISSUE THREAD

**Issue by Dream-Master** [runescapejon/AdventureBackpack2#1]
A lot of items have only the Name "Backpack Components".

![image](https://cloud.githubusercontent.com/assets/2970688/15027644/21fe657c-1245-11e6-854d-54b49d89eaf7.png)

![image](https://cloud.githubusercontent.com/assets/2970688/15027706/5e1a525a-1245-11e6-91e0-7a3d9b6bc686.png)

![image](https://cloud.githubusercontent.com/assets/2970688/15027714/676b28b6-1245-11e6-8985-769081b2fdd2.png)

Only a few examples.

Tested with Version 0.8e beta 14

**Comment by runescapejon** [comment]
XD I actually forgot this thanks ill fix it asap!

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb15
Fixed
