### ISSUE TITLE
Crash when filling water bottle from backpack on a multiplayer server

### ISSUE THREAD

**Issue by corombb** [runescapejon/AdventureBackpack2#105]
Crash log here https://pastebin.com/gaWL6NbQ

Tried just placing one empty bottle in the slot, shift clicking, etc. Anything that puts a bottle in that slot crashes the game. Can't get the issue to pop up in singleplayer unfortunately. Tried both the latest Darkona version and the latest RunescapeJon version and it crashes on both. I've also had it happen once or twice with buckets but I've been testing further with buckets and I can't reproduce the issue.

**Comment by Ugachaga** [comment]
It's not an Adventure Backpack bug, but in [beta14 ](https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9g14) I added null checks. This not help you using bottles with water, but atleast game should not crash.
