### ISSUE TITLE
Integration with HungerOverhaul

### ISSUE THREAD

**Issue by avescarelo** [runescapejon/AdventureBackpack2#109]
Hey, add please integration with HungerOverhaul.
That will add this integration?
This integration can add the weight of the backpack, for example if a player wears a full backpack, the faster it will be spent the level of food, and if empty a bit slower.

I hope this is possible)

**Comment by Ugachaga** [comment]
As far as I know, HungerOverhaul does not change the consumption of food depending on filling of inventory, so your suggestion difficult to call integration.

While it's easy to implement for, say, a backpack behind your back, in case if you have a few full backpacks in your inventory (or other containers from another mod), it already pulls on a separate mod to track all of that.
