### ISSUE TITLE
Fix localization of Tags

### ISSUE THREAD

**Issue by avescarelo** [runescapejon/AdventureBackpack2#110]
Hey, translate please this tags to Russian please
![tags](https://user-images.githubusercontent.com/26678843/28369930-466e7e7e-6c99-11e7-8903-413ea2a17d1a.png)

**Comment by Ugachaga** [comment]
Yes, localizations out of date. Some messages like you pointed need to be editable in localized file.

I will see what I can do.

**Comment by avescarelo** [comment]
Well, I'll wait. Thank you for your work. Чмок :3
If you need help in translation from English into Russian, I can help you.

**Comment by Ugachaga** [comment]
I fixed all I can on my side: [gbeta17](https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9g17)

Feel free to make pull request with Russian translation. 
Note that long lines in the tooltips section can be separated by "@" symbol.

Я сделал несколько строчек в русском переводе. Просто для примера как это работает.

**Comment by avescarelo** [comment]
Well, thank you very much. Can I help in the localization?

**Comment by Ugachaga** [comment]
Русский перевод находится по адресу `/src/main/resources/assets/adventurebackpack/lang/` в файле `ru_RU.lang`. Он довольно сильно устарел и некоторые строки требуют правки, а некоторых в нем вообще нет. Как образец нужно использовать английский `en_US.lang`.

Вкратце что нужно сделать на гитхабе: создать свой форк этого мода, отредактировать перевод, создать пулл реквест.

**Comment by avescarelo** [comment]
Я перевел [описание и подредактировал некоторые строки,](https://github.com/Darkona/AdventureBackpack2/pull/131)  также нашел пару недоработок:

1)Написано: Нажмите shift, но необходимо нажимать cntrl.
![1](https://user-images.githubusercontent.com/26678843/28740046-a74ff02e-7400-11e7-8ab6-2a4466524644.png)

2)Этих строк не было в английском файле локализации и я не смог их перевести:
![2](https://user-images.githubusercontent.com/26678843/28740105-44f0f27e-7401-11e7-86bf-2976506e8a8e.png)

**Comment by Ugachaga** [comment]
Исправил: название рюкзака будет переводиться, на шланге правильное описание клавиши. Что касается перевода всех типов рюкзаков, то тут пока оставим как есть. Есть планы по переделке системы наименований, после чего можно будет добавить и перевод.

Ты правильно создал форк, но не внёс в него изменения. Свой перевод нужно скопировать [туда](https://github.com/pingvikin/AdventureBackpack2/blob/master/src/main/resources/assets/adventurebackpack/lang/ru_RU.lang), это делается прямо в браузере. И после создать пулл реквест, адресатом указав `runescapejon/AdventureBackpack2`.

По самому переводу. Я бы назвал шланг шлангом, а jetpack реактивным ранцем (в крайнем случае паровым). И сок дыни заменил на арбузный. Там есть ещё пара опечаток, но это лучше показать в самом пулл реквесте.

**Comment by avescarelo** [comment]
> Ты правильно создал форк, но не внёс в него изменения. Свой перевод нужно скопировать туда, это делается прямо в браузере. И после создать пулл реквест, адресатом указав runescapejon/AdventureBackpack2

Спасибо большое, буду знать как это необходимо делать.

> И сок дыни заменил на арбузный.

В переводе есть сок дыни и арбузный сок, но  игре я видел только арбузный сок.
