### ISSUE TITLE
Wolf Backpack not works on Dire Wolfs from Ender Zoo

### ISSUE THREAD

**Issue by Dream-Master** [runescapejon/AdventureBackpack2#113]
Wolf Backpack not works on Dire Wolfs from Ender Zoo the mob be hostil with weared Wolf Backpack.

Tested in GTNH version 1.5.0.7 dev.

https://github.com/GTNewHorizons/NewHorizons

**Comment by Ugachaga** [comment]
Never used Wolf backpack myself. Will investigate.

**Comment by Ugachaga** [comment]
Well, Dire Wolves coded as a completely different entity that does not support the behavior of wolves.
