### ISSUE TITLE
Issue with Thermos based Server

### ISSUE THREAD

**Issue by AverageUnknown** [runescapejon/AdventureBackpack2#114]
Im using a Plugin called https://www.spigotmc.org/resources/wilderness-tp.18431/

And this mod (Beta-0.9g18 and previous versions aswell) is conflicting with it:
https://www.spigotmc.org/threads/wilderness-tp.123160/page-34#post-2632016

If you are unable to fix this would it be possible to just add a option to disable users from being able to place the backpacks as blocks?

Thanks

**Comment by Ugachaga** [comment]
So what the issue exactly? Crash log? Error log? Description of wrong behavior?

**Comment by AverageUnknown** [comment]
Basically what is happening is that the mod is affecting a plugin in a very strange way, when a backpack is in a blocks state and someone interacts with it by giving or taking a item inside of it, it throws errors (see gif for example and the pastebin for the error), it does not happen when the backpack is interacted with it inside the users inventory or "equipped"

Sorry i didn't want to spam my entire conversation i had on the plugin discussion here, thats why i provided the link to our conversation on the spigot website.

I will post the error i am getting including a gif of the actual action that causes the error.

You can go back to the spigot link to see the discussion i had with the plugin maker if you are interested or if needed.

I will also post my startup log so you can see what im working with.

Startup log:
https://pastebin.com/ETAixyXF

Error:
https://pastebin.com/7RQGmJtv

Gif:
http://i.imgur.com/0BkcqHs.gifv

If you need any other info i can provide it,

Thanks

**Comment by Ugachaga** [comment]
Is there any other unwelcome effects besides console spam?

**Comment by Ugachaga** [comment]
note for self https://github.com/Qballl/WildernessTp/blob/master/src/main/java/me/Qball/Wild/GUI/InvClick.java

**Comment by AverageUnknown** [comment]
Only console spam as i can tell, i've been watching the server like as hawk and no issues besides that.

**Comment by Ugachaga** [comment]
I assume that the reason of this spam is [that string](https://github.com/Qballl/WildernessTp/blob/master/src/main/java/me/Qball/Wild/GUI/InvClick.java#L38) from wilderness plugin:
`if (e.getInventory().getName().equalsIgnoreCase("wildtp")) {`

Tile Adventure Backpack [has no inventory name](https://github.com/runescapejon/AdventureBackpack2/blob/05d8fab76f419b42c2fb5e866ffa36bc11ad3bb5/src/main/java/com/darkona/adventurebackpack/block/TileAdventureBackpack.java#L192-L196) and return `null`. I could change it to return something reasonable but there is [hasCustomInventoryName](https://github.com/runescapejon/AdventureBackpack2/blob/05d8fab76f419b42c2fb5e866ffa36bc11ad3bb5/src/main/java/com/darkona/adventurebackpack/block/TileAdventureBackpack.java#L224-L228) method, wich return `false`, so noone should **even try** to ask for `getInventoryName`.

The correct solution would be to check for the presence of a name before ask for it (`hasCustomInventoryName`) or a rough null-check: `e.getInventory().GetName() != null`.

Right now i have no time no devenv installed, so maybe @Qballl can help you.

**Comment by Qballl** [comment]
At one point the error did show a line num and the line was if e.getInventory() == null

Edit I reread what you said and I know a quick way to fix this @JySzE Ill have this fixed soon rn Im at school and I dont know if the repo is up to date so I can't make any changes

**Comment by Eufranio** [comment]
A lot of plugins on bukkit/spigot expect inventories to have a inventory name so they can handle custom GUIs. Why wouldn't you set the name of the backpack inventory?

**Comment by AverageUnknown** [comment]
@Qballl @Ugachaga Thanks for both of your help I appreciate it.

**Comment by Qballl** [comment]
@JySzE  Here is a file containing the patch https://github.com/Qballl/WildernessTp/raw/master/target/WildTp.jar tho this problem really needs to be fixed on his end by returning something for e.getInventory.getName

**Comment by AverageUnknown** [comment]
@Qballl Error is still happening, You are right it will need to be fixed on his end. 

Thanks for going out of your way and trying to patch it on your end.

**Comment by Ugachaga** [comment]
@Eufranio rerurn `null` is pretty [common](https://github.com/ItzDennisz/Deepworld-Mod/blob/355ae5390a6767bafc8cab2e307955ff22853d44/src/main/java/Deepworld/Client/Inventory/InventoryAccessories.java) [practice](https://github.com/invizzble/ScientomicCraft/blob/98c809361e55f4559152ae4fe40ac8a4cbd0dcdc/java/com/invizzble/SC/tileEntities/TileEntityGrinder.java). Bukkit/Spigot should handle 'hasCustomInventoryName` check.

Anyway it's easy fix and even `""` better than `null`, so I will change tile inventory name when I get time.

**Comment by Qballl** [comment]
Thanks cause I did add a if (e.getInventory().getName() == null) and I guess still throwing the error
