### ISSUE TITLE
Dragon backpack dissapeared on death

### ISSUE THREAD

**Issue by Lithorn** [runescapejon/AdventureBackpack2#116]
I recently died with a dragon backpack enchanted with Soul Bound. Ive died many many times with it, but for some reason this morning the backpack was gone. We're using the latest rev of the mod, on GTNH. Extra Utilities is installed but the packs never been in the grave. There was some slabs nearby but, I died about 5 blocks below them. Do bags share inventories per player? Can I get my stuff back via recrafting?

Using adventurebackpack-1.7.10-0.9gbeta18

**Comment by Ugachaga** [comment]
Similar to https://github.com/runescapejon/AdventureBackpack2/issues/101.

Neither slabs, grave or soulbound are related to the issue. Seems something weird happens on player reconnect/respawn. It is hard to say exactly what is the source of the problem, perhaps just a high load when player respawns or something proxy-related (maybe connected with https://github.com/runescapejon/AdventureBackpack2/issues/20 too). Anyway would be good to make some sort of fail check, but do not count on me.
