### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by Nrin** [runescapejon/AdventureBackpack2#12]
Whilst wearing an adventure backpack with one non tool item on the hotbar and the rest filled with tools like wooden shovels I am able to quickly scroll through them while quickly tapping shift and this allows you to dupe the non tool item. The tools get replaced by whatever item you had on the hotbar. I tested this in both singleplayer and multiplayer and both had the same results.

**Comment by ProsperCraft** [comment]
https://github.com/Darkona/AdventureBackpack2/issues/56

**Comment by Nenluen** [comment]
These two are probably related as well:

https://github.com/Darkona/AdventureBackpack2/issues/78

https://github.com/Darkona/AdventureBackpack2/issues/67

**Comment by runescapejon** [comment]
eh can you make a quick video doing this ? Thanks

**Comment by Nrin** [comment]
I can livestream it for you if you like.

**Comment by runescapejon** [comment]
Sure link?

**Comment by Nrin** [comment]
https://www.twitch.tv/nrin

**Comment by runescapejon** [comment]
okay i seen it

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb23

**Comment by Nrin** [comment]
I'm gonna have a go at it and try my hardest to break it in singleplayer.

**Comment by Nrin** [comment]
Did you get rid of the feature completely? I can't get it to switch tools now. I've tried many different vanilla tools and the feature doesn't work at all. Honestly I'm fine if that was your goal since I dislike that feature anyway but I just want to be sure.

**Comment by runescapejon** [comment]
Wait! that was a feature ? xD i removed it but anyways if you want the store the tools you can do it here and it will render on outside of the backpack
https://gyazo.com/736180b14118f1fd986374118f894ed9

**Comment by Nrin** [comment]
LOL. Apparently it was supposed to be a feature yeah. It was supposed to allow the user to cycle through tools.

**Comment by runescapejon** [comment]
oooo i didn't like it either it annoying I'm going to keep it this way they can put the tools on that slot

**Comment by Drehverschluss** [comment]
Oh no rlly you now remove this awesome feature.....That was acctually one of my most used in that mod. Im rlly sad.

There was no better way to swep through TinkerTools as this great feature. Plz give us at least a option to toggle it on or of in the config.

MFG
(Lover of the  feature)

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases

**Comment by Dream-Master** [comment]
will be in the next Version of Gt New Horizons 1.0.8.6
