### ISSUE TITLE
1.7.10-h1 Server Crash (Thaumcraft?)

### ISSUE THREAD

**Issue by LordPinkerton** [runescapejon/AdventureBackpack2#122]
Server crash occurs when wand is placed in tool slot. (Client not affected except for loss of wand)
Server crash when Thaumcraft item put into backpack inventory. (Client not affected except server closing)
Client exception and server disconnect when shift+scroll wheel wand.

Server Crash Report
https://pastebin.com/ZQj5LPWy

**Comment by Ugachaga** [comment]
edit: nvm, i see the problem

**Comment by LordPinkerton** [comment]
Sorry I didn't respond sooner. Thank you.
