### ISSUE TITLE
Drinking a water bottle gives regeneration effect

### ISSUE THREAD

**Issue by Sir-Chi** [runescapejon/AdventureBackpack2#13]
Hey, just thought i better let you know that for some when you drink a normal water bottle it gives you a regen effect. I'm not sure if this a bug or not, but i thought it best to let you know anyways.

Thanks, SC.

Tested in the latest version (beta-24)

![2016-06-11_10 20 17](https://cloud.githubusercontent.com/assets/17249849/15984316/3e4c6a76-2fbe-11e6-8f35-13e15cef679f.png)

**Comment by runescapejon** [comment]
o.0 xD well i'll have to look into this

**Comment by Sir-Chi** [comment]
Thanks, if you need anymore info just ask :)

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb25

**Comment by Sir-Chi** [comment]
Thanks a lot for this :) much appreciated!

**Comment by Darkona** [comment]
It was actually intended ;)

**Comment by Sir-Chi** [comment]
Oh LOL! That's interesting :P I guess i should have figured, as drinking lava also gives effects. :D
