### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by avescarelo** [runescapejon/AdventureBackpack2#134]
When i put lava crystal (BloodMagic) in crafting slots, and press Shift+Q
LavaCryatal has beed dropped and will remain in BackPack
![image](https://user-images.githubusercontent.com/26678843/44748968-dcb23a00-ab19-11e8-8b8e-60c6d7649a2e.png)

**Comment by Ugachaga** [comment]
I can't reproduce it. Need more info.
Is this dupe consistent and works everytime?
Is it works with Lava Crystal taken from CreativeTab?

**Comment by Ugachaga** [comment]
I've found visual glitch when you Shift+Q Lava Crystal from holding Backpack. However it's not real dupe, remaining crystal just ghost item and will disapper when you click on it. Anyway I fix it: https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9h10

Feel free to reopen if issue persist.
