### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by avescarelo** [runescapejon/AdventureBackpack2#138]
Make plz lines in localization file for this tooltip:
![image](https://user-images.githubusercontent.com/26678843/44806795-910e9780-abd0-11e8-9f0a-8d2cf85fb20e.png)

What is it?:
![image](https://user-images.githubusercontent.com/26678843/44806984-08442b80-abd1-11e8-9afc-5022a5831154.png)

**Comment by Ugachaga** [comment]
I won't put any effort to add new features in 1.7.10 version. All I can do is accept pull request if you fix it yourself.
