### ISSUE TITLE
Backpacks disappear after death using OpenBlocks

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#17]
I have a server and i have OpenBlocks and Adventure Backpacks, both installed. When a player dies in a dimension with `keepInventory = false`, OpenBlocks place a grave on the ground, and save player's items.

But i remember that Adventure Backpacks have also a feature that place the backpack from the dead owner on the ground. I think they are spawning in the SAME place.
When i die, a OpenBlocks grave spawns, and my backpack not. Then, i lose everything inside. Is it designed to be, or this is a bug?

**Comment by runescapejon** [comment]
going to make compatible with OpenBlocks

**Comment by Eufranio** [comment]
Thank you! :smile:

**Comment by runescapejon** [comment]
Just tested this and its in the same place as my death spot was

**Comment by Eufranio** [comment]
keepInventory false? Did the grave spawn?

**Comment by runescapejon** [comment]
Yes

**Comment by Eufranio** [comment]
Hmm... Using Thermos? I tested now and again the backpack disappeared...

**Comment by runescapejon** [comment]
i test it singleplayer

**Comment by Eufranio** [comment]
Singleplayer seems work here, test in a Thermos server

**Comment by runescapejon** [comment]
https://gyazo.com/b4f3d0cceed6023e3d50d91ef1cbaef3 Just tested on thermos build 58

**Comment by Eufranio** [comment]
Hmm, did you try in the end? It's the only world that we don't have keepInventory true and the bug happened there

**Comment by runescapejon** [comment]
https://gyazo.com/248d6f303360ec389d539f764d5e0868

**Comment by Eufranio** [comment]
Hmmm, weird. I'll do more tests soon, and reopen the issue if i find the source of the bug.
Thank you by the support! :smile:
