### ISSUE TITLE
Copter flies with Water and any other Fluid.

### ISSUE THREAD

**Issue by Dream-Master** [runescapejon/AdventureBackpack2#2]
I test it and the copter flies with water. If it flies with Buildcraft Fuel this is ok but water need to be disabled.

![image](https://cloud.githubusercontent.com/assets/2970688/15027926/73e76306-1246-11e6-818c-1d06731019f8.png)

**Comment by Dream-Master** [comment]
Maybe you can add different fuels with different burn values.

Some Basic Fuel and some more advanced Fuel.

**Comment by runescapejon** [comment]
hmm maybe i can add lava also ill take a look at this

**Comment by Dream-Master** [comment]
Add Better some fuel because lave is a bit unrealistic I think. Maybe add some own fuel and make it compatible with Galacticraft and Buildcraft Fuel please. Gregtech have some Nitro Diesel which is a bit more advanced and can burned/using up more slowly.

**Comment by runescapejon** [comment]
I'll try my best

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/15029533/45939c10-124e-11e6-9f62-b40f45e70a31.png)

![image](https://cloud.githubusercontent.com/assets/2970688/15029560/6372a578-124e-11e6-86f7-060bd8ba3b56.png)

**Comment by Dream-Master** [comment]
Thanks a lot for keeping this mod alive.

**Comment by TreeT0p4** [comment]
hey whats ur modpack or server

**Comment by Dream-Master** [comment]
@killamuredya 
https://github.com/GTNewHorizons/NewHorizons

Next update we get public. Google for GT New Horizons Technic Launcher and you will find the Pack.
If you want to play on the server contact me dream-master@gmx.net

**Comment by Dream-Master** [comment]
@runescapejon 

I think lava will fit better in the Steam/Coal Backpack then in the Copter Backpack.

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-16-pre
Changed

**Comment by runescapejon** [comment]
can you send me the link to this gregtech mod

**Comment by runescapejon** [comment]
added support for BuildCraft Fuel's and Oil coming up in this update

**Comment by runescapejon** [comment]
Removed Water and lava stays for various of reasons like if someone don't like buildcraft and just want to play with the mod

**Comment by runescapejon** [comment]
Tested and compatible with BuildCraft and Galacticraft Oil and Fuel

**Comment by runescapejon** [comment]
done
https://github.com/runescapejon/AdventureBackpack2/releases

**Comment by Dream-Master** [comment]
Yes i send you GT link.

https://github.com/Blood-Asp/GT5-Unofficial

it is GT 5. GT 6 is only api open source.

**Comment by Dream-Master** [comment]
Can you please add a config option to disabled lava in the copter pack. Otherwise no one will using BC Fuel.

**Comment by runescapejon** [comment]
hmm I can see what i can do :D

**Comment by Dream-Master** [comment]
Thanks and keep up the good work.

**Comment by runescapejon** [comment]
it may take me while because I'm finishing up coding another mod called BackPack mod

**Comment by TreeT0p4** [comment]
hey dream master whats ur teamspeak

**Comment by Dream-Master** [comment]
@killamuredya 
I not have one atm.
You can contact me on irc.usrv.eu port 6667 for chatting because this isnt the right place here.

**Comment by runescapejon** [comment]
i couldn't find fuel from gregtech but what i do know oil cell's work and fine any mod's that have "oil" or "fuel" in somesort of container works fine with the copter pack

**Comment by Dream-Master** [comment]
I not suggest put oil inside but fuel is nice. If Buildcraft/GC Fuel now supported I think this is fine. 
If I think about realism a bit oil won't fit well.

**Comment by runescapejon** [comment]
eh i mainly put it for testing reasons then again i left it thinking that someone would want that as a feature i also was busy recoding this mod https://github.com/runescapejon/Minecraft-Backpack-Mod/releases

**Comment by Dream-Master** [comment]
Sure. It would be great add some config option to enable and disabled it.
I see you continue develop Eydamos Backpack Mod. This is great also because I can using mid pack packs :)

**Comment by runescapejon** [comment]
I'm trying to add a config but the way i have program the liquids is a bit hard

**Comment by Dream-Master** [comment]
I look into your code and want to ask if Coal with 0,8f have a better burn level as Fuel with 1,0f or is it the other way around?

**Comment by runescapejon** [comment]
What do you mean?

**Comment by Dream-Master** [comment]
https://github.com/runescapejon/AdventureBackpack2/blob/826d40a89042ef0e7437dc9f694f0ae32f602db1/src/main/java/com/darkona/adventurebackpack/reference/GeneralReference.java#L25

**Comment by runescapejon** [comment]
coal is for jetpack's not copterpack

**Comment by Dream-Master** [comment]
Ok understand but what the values mean?

**Comment by runescapejon** [comment]
not values there are float just google "float java define"

**Comment by Dream-Master** [comment]
Ok I understand but I not asking what float mean I want to know what it describe. Amount, viscosity, burn value.......?

May Java knowledge is very basic.

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/blob/master/src/main/java/com/darkona/adventurebackpack/inventory/InventoryCoalJetpack.java#L53-L61

**Comment by Dream-Master** [comment]
ok.

**Comment by Dream-Master** [comment]
Ok i added Gt nitrofuel by my self. Will be in the Pull request.

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases
Done I'm going to close because added a lot of other fuel for copter pack that supported with many mods 
I might make a config option for disabling lava
