### ISSUE TITLE
Dimension Blacklist

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#22]
Would be nice a config that don't let players open/access a backpack in certain dimensions. This is usefull because some players are using backpacks to transport items between overworld and witchery dream dimension...

**Comment by Eufranio** [comment]
News?

**Comment by runescapejon** [comment]
Sorry, i only made plan's to fix bug's as far as this i haven't did anything yet mainly because i was soo busy today but i will let you know if anything here

**Comment by Eufranio** [comment]
Okay

**Comment by runescapejon** [comment]
i seen Ugachaga had already added this so im going to close this if you are having any issue with new feature please make new issue thanks
