### ISSUE TITLE
Temporary loss of a bag

### ISSUE THREAD

**Issue by iLefty** [runescapejon/AdventureBackpack2#23]
If have 2 bags in inventory and place one on the any block, then the second bag (which didn't placed) vanishes from inventory. When recalling a game, the bag comes back to stock.
You will fix this unpleasant bug?
Version of mod - Beta-0.8eb28.
There is a similar bug, on servers. If to place a bag to others region (WorldGuard), then it vanished from inventory and returns when rejoining.

**Comment by runescapejon** [comment]
what do you mean by earth ?

**Comment by Eufranio** [comment]
Do you have InventoryTweaks?

**Comment by iLefty** [comment]
Yes, I have InventoryTweaks. Problem because of it?

**Comment by Eufranio** [comment]
Yes, because of the AutoRefill feature, sometimes it's buggy. Test without InvTweaks or with the feature disabled, please

**Comment by iLefty** [comment]
Perhaps you are right, thanks.

**Comment by iLefty** [comment]
Close issue.
