### ISSUE TITLE
Adventure Backpack tool slot and Battlegear2: client crash

### ISSUE THREAD

**Issue by Dream-Master** [runescapejon/AdventureBackpack2#26]
Some of my players reported it.
I know there is not Adventure Backpack in the Stack trace but maybe this items are not supported or did I report this to Draconic Evolution and Mine and Blade battle gear too ?

https://github.com/GTNewHorizons/NewHorizons/issues/750

**Comment by runescapejon** [comment]
this is a problem with Draconic Evolution and Mine and Blade battle gear's try reporting to either one of them to fix this problem sorry
