### ISSUE TITLE
Client-Server inventory sync

### ISSUE THREAD

**Issue by Ugachaga** [runescapejon/AdventureBackpack2#31]
Something wrong with visual updating backpack inventory on content changing.
As sample: Pick up stack of dirt from main inventory by lclick; put just 1 dirt to backpack by rclick; lclick 63 remaining units to same slot; backpack shows only one piece of dirt.
Or shift-click 1 dirt from main inventory to backpack; then shift-click some more (but less then 64); again shows only one piece of dirt. And so on.
Its only visual mess. After reopening backpack shows all stacks as intended.

**Comment by runescapejon** [comment]
what? I'm a  bit confuse can you demonstrated in a video ? or git or something

**Comment by Ugachaga** [comment]
![backpackinventory](https://cloud.githubusercontent.com/assets/19178671/20240294/54c3fb04-a947-11e6-9cc5-bdf1116aee20.gif)

**Comment by runescapejon** [comment]
Thanks much better understanding xD

**Comment by Ugachaga** [comment]
Seems related to https://github.com/runescapejon/AdventureBackpack2/issues/23 and perhaps to https://github.com/runescapejon/AdventureBackpack2/issues/7

**Comment by runescapejon** [comment]
This is still an issue i merged your attempt to fix it only lead to another bug which is bad
