### ISSUE TITLE
Placing bucket with liquid in a Coal Jetpack crashes client

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#40]
Crash-report: http://hastebin.com/capuliloje.coffeescript

**Comment by runescapejon** [comment]
can you try it with vanilla ? to make sure there not mod's conflict

**Comment by Ugachaga** [comment]
I can't reproduce in SSP, need more info.

**Comment by Eufranio** [comment]
Yes, there is no bugs in vanilla, but with my modpack there is: www.magitechserver.com/mods

**Comment by Eufranio** [comment]
Looks like a incompatibility between AdventureBackpacks and one of my mods that handles fluids, but I dont know which...

**Comment by Ugachaga** [comment]
I've downloaded your pack, changed adventurebackpack to 1.7.10fbeta9 and still can't reproduce crash in SSP.

**Comment by Eufranio** [comment]
Can you please send me your Technic Launcher's client ID? (Launcher options > Client ID > Copy and paste here), because I updated my pack and there is a secret build, if so I can give you access to the build and you will see the crash.

**Comment by Ugachaga** [comment]
I'd say it's modpack issue. Something very special happening, like no one fluid registered as vanilla water or something like that.

**Comment by Eufranio** [comment]
Yes, definitely a issue with me, runescapejon joined the server with me, I crashed and he didn't. Closing.
