### ISSUE TITLE
Losing backpack if BlockPlaceEvent is cancelled

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#44]
**Steps to reproduce:**

1. Have a plugin/mod (such as MyTown2 or GriefPrevention) that cancel BlockPlaceEvent
2. Give yourself a backpack, and try to place it on the ground. The event will be cancelled, the block removed from world and you won't get your backpack again.

**Comment by CyberSpongie** [comment]
This is fixed in the update dude i have tested it only with worldguard

**Comment by Eufranio** [comment]
Updated to latest Adventure Backpack from `/releases/` and it still deleting my backpack.

**Comment by Eufranio** [comment]
Well, the thing that is cancelling the event is MyTown2. AdventureBackpacks may work when the event is cancelled by bukkit but not by Forge, this may be the problem then...

**Comment by runescapejon** [comment]
it seem this happen within MyTown2 cause i tried it with WorldGuard and it pop back into my inventory but will do more testing and debugging the issue

**Comment by Eufranio** [comment]
Looks like it happens with all forge ways of cancelling the event.

**Comment by Eufranio** [comment]
No updates? =/
You can reproduce, just deny by forge was users placing Backpacks.

**Comment by Ugachaga** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9fb29
