### ISSUE TITLE
Turn the GUIs server-side

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#45]
When you open a backpack, the GUI shows up fast, like if it wouldn't asking the server for opening the container. If the PlayerInteractEvent is cancelled, the GUI still open, and cause some issues, like players being kicked for bad packet, etc...

**Comment by Ugachaga** [comment]
https://github.com/runescapejon/AdventureBackpack2/commit/b37fb8ca931b06f0fd65f707564cf506bff51a85#diff-8693e65f6f19022b1092ca0db67fd25aL274

Should be solved.
