### ISSUE TITLE
Update mod to latest version?

### ISSUE THREAD

**Issue by Fenway17** [runescapejon/AdventureBackpack2#51]
Just want to know whether youre gonna work on getting this mod available for the latest version of MC?

**Comment by runescapejon** [comment]
Sorry but i am super busy with other stuff and unable to update the mod, it does take time cause once you update the mod your going to have about 2,000+ error's see i have barely no time for it but however if you enjoy this version 1.7.10 you can either update it yourself or just wait whenever i have time for it
