### ISSUE TITLE
Coal Jetpack not have any texture and can not find symbole getWaterTank

### ISSUE THREAD

**Issue by Dream-Master** [runescapejon/AdventureBackpack2#6]
In my dev inviroment (idea) i not have any texture.

![image](https://cloud.githubusercontent.com/assets/2970688/15159806/b7da4010-16f6-11e6-8f7a-636628450623.png)

Tested with newest Version

![image](https://cloud.githubusercontent.com/assets/2970688/15159822/cc4ca560-16f6-11e6-8bcc-190a63a11de3.png)

I get two erros which says

Error:(195, 30) java: cannot find symbol
  symbol:   method getWaterTank()
  location: variable inv of type com.darkona.adventurebackpack.inventory.InventoryCoalJetpack.

**Comment by Dream-Master** [comment]
Ok find out why the item not have any texture because texture name are wrong. I change Water to Coal Tank and test it now.

**Comment by runescapejon** [comment]
is that you touch the code in the latest jar even the old once's texture works fine

**Comment by Dream-Master** [comment]
Send a pull request which works for me.

**Comment by runescapejon** [comment]
`modelTexture = Resources.modelTextures("coalJetpack").toString();
         return modelTexture;
    }

```
  @Override           @Override
  @SideOnly(Side.CLIENT)              @SideOnly(Side.CLIENT) 
  public ResourceLocation getWearableTexture(ItemStack wearable)            
  public ResourceLocation getWearableTexture(ItemStack wearable)
  {         
```

  {
       return Resources.modelTextures("coalJetpack");`

`setUnlocalizedName("coalJetpack");`
that is why you had a texture error why did you bother putting a C lower cap

**Comment by Dream-Master** [comment]
No the Image have the old name "SteamJetack" i guess you renamed it before. I take the c lower cap to make it similar to the copterPack.

https://github.com/runescapejon/AdventureBackpack2/pull/9/commits/7f1f64e76cd6c3f8ba1bbf8024c7ec8f6b6cd648

**Comment by runescapejon** [comment]
oh  okay
