### ISSUE TITLE
[Request]First time spawn with loot

### ISSUE THREAD

**Issue by Jake1702** [runescapejon/AdventureBackpack2#65]
Hey, I saw on the forum you said to post it here, so here it is. I'm a bit lazy so I'm basically copy pasting from the forum post.

> Hey. Nice to see someone is keeping this mod updated, there is one feature I'd like to suggest, though. The ability to give the player a backpack with certain items in it when they spawn in the world for the first time. It would be really useful for modpack creation so that the player is surprised when opening the backpack for the first time. I'm not sure how hard this would be to implement, as I don't really have experience with programming. But, no harm in suggesting it right? :)

**Comment by Ugachaga** [comment]
Won't happen. Use NBT to change inventory.
