### ISSUE TITLE
Copterpack eating up Buckets

### ISSUE THREAD

**Issue by Dream-Master** [runescapejon/AdventureBackpack2#7]
If you try to get the fluid back and put a Bucket in the Inventory slot the Bucket is eating up and gone.

**Comment by Dream-Master** [comment]
Gregtech cells (testet with Oil cells) works well and you get it back.
Oil cans and capsule from Forestry works well too.
Ic2 universal fluidcells are not supportet.

**Comment by runescapejon** [comment]
what kinda of fluid ?

**Comment by Dream-Master** [comment]
I try with Water and Lava Buckets.

**Comment by runescapejon** [comment]
i don't the problem can you show it in a video or gif or something so  i can see what your talking about

**Comment by Dream-Master** [comment]
When I be back home will make a vid.

**Comment by Dream-Master** [comment]
Will test with your new version and report then.

**Comment by Dream-Master** [comment]
Sorry not find th time to do it.

**Comment by Dream-Master** [comment]
I guess it's fixed. I cant reproduced it.

**Comment by runescapejon** [comment]
ok
