### ISSUE TITLE
Somehow disabled Tool Cycling

### ISSUE THREAD

**Issue by Taikira** [runescapejon/AdventureBackpack2#71]
Tools were cycling properly at first but for some reason when using command line to switch game modes it disabled (even checking command history showed no wrong commands). Now sneak+mouse wheel does nothing. Please help.

**Comment by Ugachaga** [comment]
Try to press BackpackToggleActionKey ('N' by default).

**Comment by Taikira** [comment]
omg I feel like an idiot xd Thanks so much
