### ISSUE TITLE
Dupe :>

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#74]
[GIF](https://cdn.discordapp.com/attachments/215217656670715904/287724496247455745/backpacks.gif)

As you can see, if you drop the backpack and open it's GUI quick, you will be able to interact with the items, and drop them. I suggest cancelling the item move event instead just blocking all the slots.

**Comment by Ugachaga** [comment]
Almost impossible reproduce in dev. Possible fixed at [28pre4](https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9fb28). 
Does it also work for jetpack/copter?

**Comment by Ugachaga** [comment]
Ok, copypasted solution for other packs. Should be fixed now. Reopen if issue still presist.
