### ISSUE TITLE
Shift key not working as intended

### ISSUE THREAD

**Issue by nVentis** [runescapejon/AdventureBackpack2#8]
Whenever you try to use the shift key with AdventureBackpack2 items, be it the hose which can be used to interact with the backpack's tanks, or an(y) item that is placed in the green tool slots within the backpack in order to swap between the tools by scrolling as it was working before, that shift key doesn't seem to have any function anymore.
EDIT: Seems as if this issue has been existing since beta10.
EDIT2: Just built the current AdventureBackpack2-master (Version 0.8d) and found out that the bug does not exist there.

**Comment by nVentis** [comment]
It seems as if the first if statement is the reason for the "bug" appearing.

```
EntityClientPlayerMP player = mc.thePlayer;
boolean hasCape = player.func_152122_n();
hasCape = event.buttonstate && hasCape;
@SuppressWarnings("unused")
float f4;

if (hasCape && !player.isInvisible() && !player.getHideCape())
if (player != null && !player.isDead && player.isSneaking()){
    // other code following
}
```

I'm certainly not an expert at Java and am only familiar with web development, but may I ask what that Player.func_152122_n() method is supposed to do? The rest seems to be self-explaining.

EDIT: Tried building ebeta10 with the specific line removed and the behaviour ingame is now as it was back in "the old version". However, when trying to build the current version ebeta17, gradlew returns "some errors" even when the source is not touched at all. Would another issue here on GitHub be neccessary to solve that problem?

**Comment by runescapejon** [comment]
keep EntityClientPlayerMP player = mc.thePlayer; do not removed that piece of the code because you need it for 
`if (player != null && !player.isDead && player.isSneaking())
            {
                ItemStack backpack = Wearing.getWearingBackpack(player);
                if (backpack != null && backpack.getItem() instanceof ItemAdventureBackpack)
                {`
reason why i label it bug because if i were to removed it some items you were to shift mouse wheel moving you can mess up your item like example shift + mouse wheel moving with Diamond  Hoe

**Comment by nVentis** [comment]
Thank you for your reply!

I was actually referring to this line (the line before the one you pointed out)

`if (hasCape && !player.isInvisible() && !player.getHideCape())`

that, when removed, made everything working as before. If I keep that line, neither changing the mode of the Hose (item) nor selecting one of the tools I put in the backpack work. I tried out removing that line and it seems to be working as it was in the last "official" version.

My final question would really be about building ebeta17 with this line removed, but this seems to fail (though the error seems to be unrelated to that). I hope it's ok that I attach the error log to this comment. Otherwise, I feel free to ask, and I will create a separate issue :)

[ebeta17 Build Error.txt](https://github.com/runescapejon/AdventureBackpack2/files/258207/ebeta17.Build.Error.txt)

**Comment by Dream-Master** [comment]
@nVentis 
yes i got this error too. I try to fix it with the pull request.

**Comment by nVentis** [comment]
Thank you! I'm looking forward to your solution.

**Comment by Dream-Master** [comment]
The Steam Tank not shown as Steam tank and have a water fluid Texture but all the other things works fine. The Hose thing I can't fix. My Java knowledge is just very basic.

**Comment by runescapejon** [comment]
I have the hose fix and re-added feature
https://gyazo.com/3143660f98f48177dc671fb0ff26fd41
but i ran to a problem fast scroll wheel and you lose the item's it will take a while to debug the problem and fix it

**Comment by runescapejon** [comment]
new update coming out soon to sort out all of these bugs

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases
Fixed
