### ISSUE TITLE
bug with backpack

### ISSUE THREAD

**Issue by hhheeexxx** [runescapejon/AdventureBackpack2#96]
open backpack
move in item
close backpack
put backpack in first hotbar slot
open backpack
mouseover item press 1 key
close backpack
open backpack
and item stay in backpack too

**Comment by Ugachaga** [comment]
Nice dupe, thank for sharing. :) Strange noone reporting this before.
Will look into it after weekend.

**Comment by Ugachaga** [comment]
fixed https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9g10
